Feature/issue 134 user dto
A-fume/A.fume.Server pull request #135
Opened 2021-08-08 01:44 UTC by heesung6701

User 관련 변경사항 있어서 PR 올립니다. 변경사항은 아래와 같습니다.
리뷰 부탁드립니다!

- User 관련 DTO 추가
- UserDao 테스트 코드 수정
- UserService 테스트 코드 추가
- UserConteroller 테스트 코드 추가
- test용 mock 객체 파일 생성
- DTO 중 validTest가 필요한 경우는 Test폴더내 dto파일을 만들고 확장 해서 사용.

2021-08-08 10:04 UTC, ChoHadam requested changes
고생많으셨습니다 🙌
간단한 수정사항 확인해보시면 될 것 같습니다!

2021-08-08 10:54 UTC, heesung6701 commented on test/lib/token.mock.js
> +        phone: '010-2081-38',
확인했습니다!! Phone 을 제가 혼동해서 넣은거 같네요! 수정하겠습니다!

2021-08-08 10:54 UTC, heesung6701 commented on test/lib/token.spec.js
>              phone: '010-2081-38',
반영하겠습니다!

2021-08-08 10:54 UTC, heesung6701 commented on test/lib/token.spec.js
>          phone: '010-2081-38',
반영하겠습니다!

2021-08-08 10:54 UTC, heesung6701 commented on test/lib/token.spec.js
>          phone: '010-2081-38',
반영하겠습니다!

2021-08-08 10:54 UTC, heesung6701 commented on test/lib/token.spec.js
>              phone: '010-2081-38',
반영하겠습니다!

2021-08-08 10:54 UTC, heesung6701 commented on data/dto/TokenPayloadDTO.js
> +        this.phone = phone;
반영하겠습니다!

2021-08-08 10:55 UTC, heesung6701 commented on test/controller/User.spec.js
> +        phone: '010-2081-38',
반영하겠습니다!

2021-08-08 10:55 UTC, heesung6701 commented
@ChoHadam 리뷰 주신 내용 수정하여서 반영했습니다!

2021-08-08 12:09 UTC, ChoHadam approved these changes
LGTM :)

2021-08-08 12:22 UTC, merged

2021-08-16 10:16 UTC, ChoHadam commented on controllers/User.js
> +module.exports.setUserService = (userService) => {
🙋‍♀️❓ 혹시 setUserService는 어떤 경우를 위해서 작성한 코드인지 알 수 있을까요?

2021-08-16 10:18 UTC, heesung6701 commented on controllers/User.js
> +module.exports.setUserService = (userService) => {
TestCode에서 Service를 주입시켜주기 위해서 만든 코드입니다!